### ISSUE TITLE
"cv-inline-object/span"  removes after inserting new content!!

### ISSUE THREAD

**Issue by hajarghaem** [FontoXML/fontoxml-development-tools#1]
Dear,
it is not an issue but a question regarding the way fontoxml works. I'd like to know what happen when we want to change/edit a content in fontoxml editor. I see that the code changes. In fact when I select the current content it is inside:
<cv-content><cv-inline-object node-id="7" cv-layout="inline"><span class="fontoxml-text-placeholder" operation-name="select-node" operation-context-node-id="7" contenteditable="false">Type your content</span><chrome-selection-workaround></chrome-selection-workaround></cv-inline-object></cv-content>

but when I add a new content then it changes:

<cv-content>new cuntent<span class="cursor">​​</span></cv-content>

I want to know what action happens there and what is the reason for this change.

Thanks in advance,
Kind regards,
Hajar

**Comment by ThomasBrekelmans** [comment]
Hi Hajar,

I'm afraid I don't quite understand your question. I think you might have a question for your support contact at FontoXML. I don't think this question is related to this repository so I'm going to close this issue for now.

Please send your inquiry to your contact at FontoXML if you need further assistance.

Kind regards,
Thomas Brekelmans
Team Lead @ FontoXML (Platform/SDK development)
